### PR TITLE
Update get-access-to-and-back-up-a-former-user-s-data.md

### PR DESCRIPTION
**Pull request by nenonix**
Fixes issues with npsptechusa patch-5 in terms of headings, grammar, style, formatting and links. Other issues also fixed. Content in intro section was a repeat of content in previous article (remove-former-employee) or not in keeping with MS style  (If merged will require fixes to links to this article in https://docs.microsoft.com/office365/admin/add-users/remove-former-employee). Resolves https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/115

### CODE REVIEW

**Comment by mypil** [comment]
linked to PR - https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/332

**Comment by mypil** [comment]
@kenwith - this is the copy edit review and changes done by @nenonix in relation to closed PR #312 which linked to https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/332 that @npsptechusa created. Can you please help us on how the content can be merged?

Thank you.

**Comment by mypil** [comment]
@npsptechusa - can you please merge this? this is a commit made by nenonix on your fork for the content edit review. thanks.

**Review by parikhsfdc — APPROVED** [review]
Get Access to Former User Data

**Pull request merged**
